name: Flush Cache

on:
  release:
    types: [published]

jobs:
  purge-jsdelivr-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/bluesky.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/button.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/distico.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/facebook.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/faq.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/index.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/instagram.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/leggianche.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/mediahubPhoto.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/preview.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/product.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/reddit.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/searchPublicApi.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/shortcodeList.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/spoiler.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/survey.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/tiktok.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/tmdb.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/trivia.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/twitter.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/widgetbay.js
            https://cdn.jsdelivr.net/gh/The-3Labs-Team/tinymce-laravel-shortcode-plus@2/src/youtube.js
            
